services:
  hwbehat.drupal.authentication_manager:
    class: HelloWorldDevs\Behat\Manager\CustomDrupalAuthenticationManager
    arguments:
      - "@mink"
      - "@drupal.user_manager"
      - "@drupal.drupal"
      - "%mink.parameters%"
      - "%drupal.parameters%"
    tags:
      - { name: drupal.authentication_manager }
  drupal.context.environment.reader:
    class: Drupal\DrupalExtension\Context\Environment\Reader\Reader
    arguments:
      - "@drupal.drupal"
      - "%drupal.parameters%"
    tags:
      - { name: environment.reader }
