parameters:
  # Drupal authentication manager.
  drupal.authentication_manager.class: Drupal\DrupalExtension\Manager\DrupalUserManager

services:
  drupal.drupal:
    class: Drupal\DrupalDriverManager
    arguments:
      - {}
      - "@drupal.random"

  drupal.user_manager:
    class: Drupal\DrupalExtension\Manager\DrupalUserManager

  drupal.random:
    class: Drupal\Component\Utility\Random

  drupal.authentication_manager:
    class: "%drupal.authentication_manager.class%"
    arguments:
      - "@mink"
      - "@drupal.user_manager"
      - "@drupal.drupal"
      - "%mink.parameters%"
      - "%drupal.parameters%"
